[project]
name = "eodms-cli"
version = "3.6.3"
description = "The EODMS-CLI script is used to search, order and download imagery from the EODMS using the REST API (RAPI) service."
authors = [
    { name = "Kevin Ballantyne", email = "kevin.ballantyne@canada.ca" }
]
license = { text = "MIT LicenseCopyright (c) His Majesty the King in Right of Canada, as represented by the Minister of Natural Resources, 2025.Permission is hereby granted, free of charge, to any person obtaining a copyof this software and associated documentation files (the \"Software\"), to dealin the Software without restriction, including without limitation the rightsto use, copy, modify, merge, publish, distribute, sublicense, and/or sellcopies of the Software, and to permit persons to whom the Software isfurnished to do so, subject to the following conditions:The above copyright notice and this permission notice shall be included in allcopies or substantial portions of the Software.THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS ORIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THEAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHERLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THESOFTWARE." }
readme = "README.md"
requires-python = ">=3.6"
[tool.poetry.dependencies]
py-eodms-rapi  = ">=1.7.0"
requests = ">=2.23.0"
dateparser = ">=1.0.0"
geomet = ">=0.3.0"
click = ">=8.0.1"
shapely = ">=1.8.1"
python-dateutil = ">=2.8.1"
tqdm = ">=4.59.0"
numpy = "*"
packaging = "*"
colorama = "*"


[tool.poetry]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
